name: Crawler Workflow

on:
  schedule:
    - cron: "0 */3 * * *" # This runs every 3 hours
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        run: python crawler.py
